.github/workflows/npm.yml, .github/workflows/pages.yml
=> Add GitHub workflows

src/lib/detect.js
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11
close #78
=> fix(UA): distinguish between Windows 10/11

packages/artalk/package.json, packages/artalk/src/api/index.ts, packages/artalk/src/api/request.ts, packages/artalk/src/components/layer.ts, packages/artalk/src/components/list-lite.ts, packages/artalk/src/components/sidebar-layer.ts, packages/artalk/src/lib/checker/admin-checker.ts, packages/artalk/src/lib/checker/captcha-checker.ts, packages/artalk/src/lib/checker/index.ts, packages/artalk/src/lib/ui.ts, packages/artalk/src/style/main.less, packages/artalk/types/event.d.ts
关联：https://github.com/ArtalkJS/ArtalkGo/commit/14661ed00b0bdbe346b8ea577c028e4c71a256a0
https://www.geetest.com/adaptive-captcha
=> 支持 Geetest 极验

packages/artalk/index.html, packages/artalk/src/components/pagination.ts, packages/artalk/src/style/_color.less
follow [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/Translations/WCAG21-zh/)
=> perf(a11y): improve color contrast and add aria-label

README.en.md, README.md, packages/artalk-sidebar/src/admin/page-list.ts, packages/artalk/src/api/request.ts, packages/artalk/src/artalk.ts, packages/artalk/src/components/action-btn.ts, packages/artalk/src/components/comment.ts, packages/artalk/src/components/dialog.ts, packages/artalk/src/components/editor.ts, packages/artalk/src/components/html/list.html, packages/artalk/src/components/list-lite.ts, packages/artalk/src/components/list.ts, packages/artalk/src/components/read-more-btn.ts, packages/artalk/src/context.ts, packages/artalk/src/defaults.ts, packages/artalk/src/i18n/en.ts, packages/artalk/src/i18n/index.ts, packages/artalk/src/i18n/zh-CN.ts, packages/artalk/src/lib/checker/admin-checker.ts, packages/artalk/src/lib/checker/captcha-checker.ts, packages/artalk/src/lib/checker/index.ts, packages/artalk/src/lib/component.ts, packages/artalk/src/lib/utils.ts, packages/artalk/types/artalk-config.d.ts
[packages/artalk/src/i18n/](https://github.com/ArtalkJS/Artalk/tree/i18n/packages/artalk/src/i18n)
=> i18n: Add basic internationalization support

packages/artalk-sidebar/src/admin/page-list.ts, packages/artalk-sidebar/src/admin/site-list-floater.ts, packages/artalk-sidebar/src/admin/site-list.ts, packages/artalk-sidebar/src/sidebar-views/comments-view.ts, packages/artalk-sidebar/src/sidebar-views/pages-view.ts, packages/artalk-sidebar/src/sidebar-views/sites-view.ts, packages/artalk-sidebar/src/sidebar-views/transfer-view.ts, packages/artalk/src/api/request.ts, packages/artalk/src/artalk.ts, packages/artalk/src/comment/actions.ts, packages/artalk/src/comment/render.ts, packages/artalk/src/context.ts, packages/artalk/src/editor/editor.ts, packages/artalk/src/editor/plugs/header-input-plug.ts, packages/artalk/src/editor/plugs/upload-plug.ts, packages/artalk/src/layer/sidebar-layer.ts, packages/artalk/src/lib/checker/admin-checker.ts, packages/artalk/src/lib/checker/captcha-checker.ts, packages/artalk/src/lib/checker/index.ts, packages/artalk/src/list/list-lite.ts, packages/artalk/src/list/list.ts, packages/artalk/types/context.d.ts, packages/artalk/types/event.d.ts
=> refactor: Use Mediator Pattern

packages/artalk/src/artalk.ts, packages/plugin-katex/main.ts
=> refactor(func-use): Use lowercase function name instead

package.json, packages/artalk-sidebar/package.json, packages/artalk/package.json, packages/artalk/types/index.d.ts, packages/artalk/vite-base.config.ts, packages/plugin-katex/index.html, packages/plugin-katex/package.json, pnpm-lock.yaml
=> fix: Use vite-plugin-dts to generate d.ts file

packages/plugin-lightbox/README.md, packages/plugin-lightbox/global.d.ts, packages/plugin-lightbox/index.html, packages/plugin-lightbox/main.ts, packages/plugin-lightbox/package.json, packages/plugin-lightbox/tsconfig.json, packages/plugin-lightbox/vite.config.ts, pnpm-lock.yaml
=> feat: plugin-lightbox to integrate lightbox in Artalk

packages/artalk/src/lib/ui.ts, packages/artalk/src/list/list-lite.ts
=> refactor(list-lite): merge show/hide loading functions into setLoading

.circleci/config.yml, .github/workflows/npm.yml, .github/workflows/pages.yml, package.json, packages/artalk/vite.config.ts, pnpm-lock.yaml
=> chore(deps): upgrade Vite to v3

packages/artalk/src/comment/render.ts, packages/artalk/src/components/pagination.ts, packages/artalk/src/editor/editor.ts, packages/artalk/src/layer/sidebar-layer.ts, packages/artalk/src/list/list.ts, packages/artalk/src/style/main.less
=> refactor: remove style importing from ts code file

packages/artalk/src/artalk.ts
=> fix(layer): remove useless append the sidebar layer to root element

packages/artalk-sidebar/src/components/Tab.vue, packages/artalk-sidebar/src/pages/comments.vue, packages/artalk-sidebar/src/stores/nav.ts
=> feat(sidebar): comment search in sidebar

packages/artalk/src/comment/render.ts, packages/artalk/types/artalk-config.d.ts
=> feat(conf): add avatarURLBuilder config option

packages/artalk-sidebar/components.d.ts, packages/artalk-sidebar/src/App.vue, packages/artalk-sidebar/src/components/PageEditor.vue, packages/artalk-sidebar/src/components/Pagination.vue, packages/artalk-sidebar/src/components/PreferenceGrp.vue, packages/artalk-sidebar/src/components/Tab.vue, packages/artalk-sidebar/src/components/UserEditor.vue, packages/artalk-sidebar/src/pages/pages.vue, packages/artalk-sidebar/src/pages/settings.vue, packages/artalk-sidebar/src/pages/sites.vue, packages/artalk-sidebar/src/pages/users.vue, packages/artalk-sidebar/src/stores/nav.ts, packages/artalk-sidebar/src/style.scss, packages/artalk-sidebar/typed-router.d.ts, packages/artalk/src/api/user.ts, packages/artalk/types/artalk-data.d.ts
=> feat(sidebar): user management gui

.eslintrc.js, packages/artalk/src/api/index.ts, packages/artalk/src/artalk.ts, packages/artalk/src/context.ts, packages/artalk/src/defaults.ts, packages/artalk/src/editor/editor.ts, packages/artalk/src/editor/plugs/upload-plug.ts, packages/artalk/src/lib/stat.ts, packages/artalk/src/list/list-lite.ts, packages/artalk/src/list/list.ts, packages/artalk/types/context.d.ts, packages/artalk/types/event.d.ts
=> feat(conf): enable frontend config provider by default

Makefile, artalk.example.simple.yml, artalk.example.yml, artalk.example.zh-CN.yml, go.mod, i18n/en.yml, i18n/zh-CN.yml, internal/config/config.go, internal/core/core.go, internal/i18n/gen/main.go, internal/i18n/i18n.go, main.go, server/middleware/site_origin.go
=> feat(i18n): add i18n support for backend

.github/workflows/docker.yml, BACKEND.md, README.en.md, README.md, docker-compose.yml, docs/guide/backend/docker.md, docs/guide/deploy.md, scripts/docker-build.sh
=> chore: revert the rename of image on dockerhub

internal/config/config.go, internal/email/queue.go, internal/notify_launcher/init.go
related https://github.com/ArtalkJS/ArtalkGo/pull/52
=> fix(email): email queue initialization issue

server/handler/admin_comment_edit.go
=> fix(api): comment IP data loss after editing (#491)

ui/packages/artalk/src/editor/submit.ts
=> fix(editor): prevent editor reset on comment failure (#492)

docs/guide/extras.md
=> docs(extras): add deploy guide for fly.io

internal/db/db.go, internal/db/db_test.go, internal/db/dsn.go, internal/db/dsn_test.go, internal/db/logger/logger.go
=> fix(db): fix dsn strings for mysql connections (#541)

ui/packages/artalk/src/editor/plug-manager.ts
=> fix(ui): fix plug cannot disable issue (#558)

internal/config/base.go
=> feat(config): support load env variables as config (#559)

server/handler/captcha.go, server/middleware/limiter/limiter.go
=> fix(captcha): image captcha base64 response issue

cmd/admin.go, cmd/base.go, cmd/config.go, cmd/export.go, cmd/gen.go, cmd/import.go, cmd/server.go, cmd/upgrade.go, cmd/version.go
=> fix(cmd): remove app instance creation when mini boot

ui/packages/artalk/src/style/comment.scss, ui/packages/artalk/src/style/editor.scss, ui/packages/artalk/src/style/list.scss, ui/packages/artalk/src/style/main.scss
fixes #565
related to https://github.com/requarks/wiki/discussions/6015
=> perf(style): modify `z-index` less than 5

internal/core/base.go
=> perf(config): add error message for timezone setting

conf/artalk.example.simple.yml, conf/artalk.example.yml, conf/artalk.example.zh-CN.yml, docs/guide/backend/config.md, internal/config/config.go, internal/db/dsn.go, internal/db/dsn_test.go
=> feat(config): add `db.ssl` to enable db ssl mode

ui/packages/artalk/src/style/list.scss
=> fix(style): fix copyright text overlay on send button

ui/packages/artalk/src/plugins/list/no-comment.ts
=> fix(ui/conf): sanitize `noComment` conf option for security

docs/guide/extras.md
[按该Issue添加文档](https://github.com/ArtalkJS/Artalk/issues/647)
=> 添加render.com部署指南文章链接

ui/packages/artalk/src/components/checker/index.ts, ui/packages/artalk/src/layer/index.ts, ui/packages/artalk/src/layer/layer-manager.ts, ui/packages/artalk/src/layer/layer.ts, ui/packages/artalk/src/layer/scrollbar-helper.ts, ui/packages/artalk/src/layer/sidebar-layer.ts, ui/packages/artalk/src/layer/wrap.ts, ui/packages/artalk/src/plugins/admin-only-elem.ts, ui/packages/artalk/src/service.ts
#660
vuepress-theme-hope/vuepress-theme-hope#3592
=> refactor(ui/layer): better layer implements and independence

ui/packages/artalk-sidebar/src/global.ts, ui/packages/artalk/src/api/_base.ts, ui/packages/artalk/src/api/_options.ts, ui/packages/artalk/src/api/_request.ts, ui/packages/artalk/src/api/comment.ts, ui/packages/artalk/src/api/upload.ts, ui/packages/artalk/src/api/user.ts, ui/packages/artalk/src/components/checker/admin.ts, ui/packages/artalk/src/components/checker/index.ts, ui/packages/artalk/src/components/error-dialog.ts, ui/packages/artalk/src/config.ts, ui/packages/artalk/src/context.ts, ui/packages/artalk/src/layer/sidebar-layer.ts, ui/packages/artalk/src/lib/user.ts, ui/packages/artalk/src/plugins/admin-only-elem.ts, ui/packages/artalk/src/plugins/conf-remoter.ts, ui/packages/artalk/src/plugins/editor/_kit.ts, ui/packages/artalk/src/plugins/editor/closable.ts, ui/packages/artalk/src/plugins/editor/emoticons.ts, ui/packages/artalk/src/plugins/editor/header-link.ts, ui/packages/artalk/src/plugins/editor/header-user.ts, ui/packages/artalk/src/plugins/editor/state-edit.ts, ui/packages/artalk/src/plugins/editor/submit-add.ts, ui/packages/artalk/src/plugins/editor/upload.ts, ui/packages/artalk/src/plugins/list/sidebar-btn.ts, ui/packages/artalk/src/service.ts, ui/packages/artalk/types/event.ts
=> refactor(ui/user): user class no longer globally singleton

.circleci/conditional_config.yml, .circleci/config.yml, .github/workflows/build-frontend.yml, .github/workflows/docs-cn.yml, .github/workflows/test-frontend.yml, Dockerfile, scripts/build-frontend.sh
=> test(ci): migrate UI tests back to Github Actions

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.en.md, README.md
Important: The minimal development node version is now 18
=> chore: update readme

ui/packages/artalk-sidebar/src/components/PreferenceArr.vue, ui/packages/artalk-sidebar/src/components/PreferenceGrp.vue, ui/packages/artalk-sidebar/src/components/PreferenceItem.vue, ui/packages/artalk-sidebar/src/lib/settings-option.ts, ui/packages/artalk-sidebar/src/lib/settings.ts, ui/packages/artalk-sidebar/src/pages/settings.vue
=> fix(ui/sidebar): refactor settings and fix save issue (#677)

ui/packages/artalk-sidebar/index.html, ui/packages/artalk/src/components/checker/captcha-renders.ts, ui/packages/artalk/src/layer/sidebar-layer.ts
=> fix(ui): add `referrerpolicy` attribute for iframe (#687)

ui/artalk/src/config.ts
=> fix: don't mutate Default in-place

ui/artalk/src/context.ts, ui/artalk/src/types/context.ts, ui/plugin-lightbox/main.ts
=> refactor(ui/ctx): add `getComments` and `getCommentNodes` in context

ui/artalk/src/plugins/editor-kit.ts
Signed-off-by: Frost Ming <me@frostming.com>
This can be reproduced in the artalk sidebar reply comment editor
=> fix: prevent propagation in editor

conf/artalk.example.simple.yml, conf/artalk.example.yml, conf/artalk.example.zh-CN.yml, docs/docs/guide/backend/admin_notify.md, i18n/en.yml, i18n/zh-CN.yml, i18n/zh-TW.yml, internal/config/config.go, internal/notify_pusher/checker.go, internal/notify_pusher/email.go, internal/notify_pusher/multi.go, internal/notify_pusher/operate.go
```yaml
admin_notify:
notify_pending: false
```
=> feat(notify): add `notify_pending` config option (#728)

ui/artalk-sidebar/src/main.ts, ui/artalk/src/context.ts, ui/artalk/src/list/page.ts, ui/artalk/src/plugins/dark-mode.ts, ui/artalk/src/plugins/editor-kit.ts, ui/artalk/src/plugins/editor/index.ts, ui/artalk/src/plugins/list/copyright.ts, ui/artalk/src/plugins/list/dropdown.ts, ui/artalk/src/plugins/list/sidebar-btn.ts, ui/artalk/src/plugins/list/unread-badge.ts, ui/artalk/src/plugins/stat.ts, ui/artalk/src/plugins/version-check.ts, ui/artalk/src/service.ts, ui/artalk/src/types/context.ts, ui/artalk/src/types/event.ts
=> perf(ui/conf): support for watching partial changes in config with `watchConf()`

.github/workflows/build-nightly.yml, i18n/fr.yml
=> French translation

docker-entrypoint.sh, internal/dao/cook.go, internal/dao/migrate.go, internal/dao/query_find.go, internal/dao/query_find_test.go, internal/entity/comment.go, scripts/benchmark.sh, server/handler/comment_create.go, server/handler/comment_list.go, server/handler/comments_get/base.go, server/handler/comments_get/utils_list.go, server/handler/stat.go
QPS theory increased by 46%
Latency theory reduced by 29%
The test case is the first page of the official website's comment data pagination, SQLITE database (caching is turned off).
=> perf(db): optimize `N+1` query in comment list

docs/docs/guide/cases.md, docs/docs/guide/extras.md
=> 添加新的扩展阅读文章与案例博客

conf/artalk.example.simple.yml, conf/artalk.example.yml, conf/artalk.example.zh-CN.yml, docs/docs/.vitepress/config.ts, docs/docs/guide/backend/config.md, docs/docs/guide/frontend/config.md, docs/docs/guide/frontend/img-lazy-load.md, ui/artalk/src/lib/marked-renderer.ts, ui/artalk/src/lib/marked.ts, ui/artalk/src/lib/sanitizer.ts, ui/artalk/src/plugins/markdown.ts, ui/artalk/src/types/config.ts
Refer to: https://artalk.js.org/guide/frontend/img-lazy-load.html
=> feat(ui/img_lazyload): add support for lazy loading images in comments

.goreleaser.yml, scripts/build-frontend.sh
fixes https://github.com/NixOS/nixpkgs/pull/308423
=> feat(ci): include frontend dist files in release

docs/docs/.vitepress/config.ts, docs/docs/develop/compatibility.md, eslint.config.mjs, pnpm-lock.yaml, ui/artalk/package.json, ui/artalk/src/api/fetch.ts
refer to https://artalk.js.org/develop/compatibility.html
=> refactor(ui/deps): remove `abortcontroller-polyfill`

pnpm-lock.yaml, ui/artalk-sidebar/src/components/Tab.vue, ui/artalk/package.json, ui/artalk/src/lib/marked.ts, ui/artalk/src/types/config.ts, ui/artalk/src/types/context.ts
- Add exported types from marked package for Artalk's Context and Config
=> refactor(ui/marked): replace pkg-level marked with new class instance

ui/artalk/src/lib/detect.ts
=> feat(UA): support OpenHarmony and browsers on it
