- .eslintrc.js
- package.json
- pnpm-lock.yaml
I added the relevant rules based on the browser compatibility written in the documentation
https://artalk.js.org/guide/intro.html#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9=
-----
But there is an error about compatibility when I execute eslint, should we update the documentation now or update the code?
```
Artalk\packages\artalk\src\api\index.ts
97:18  error  AbortController is not supported in Opera 50, iOS Safari 11.0-11.2, Chrome 63  compat/compat
```
> chore: add browser compatibility lint

- .github/renovate.json
---
It should automatically use the Angular Conventional Commit Style if it can detect it. And this should only be a temporary alternative for [pnpm if GitHub's own dependabot doesn't support it yet](https://github.com/dependabot/dependabot-core/issues/1736), but if it's doing well just let it keep doing it
> chore: use renovate to auto update deps

- ui/packages/artalk-sidebar/src/pages/comments.vue
This pr does one thing: adjusts the order of items in the sidebar navigation bar for non-admin users, and shows all comments by default
|Before|Now|
|:----|:----|
| <ul><li>Mentions (default)</li><li>All</li><li>Mine</li><li>Pending</li></ui> | <ul><li>All (default)</li><li>Mentions</li><li>Mine</li><li>Pending</li></ui> |
> fix: sidebar navigation sorting

- conf/artalk.example.simple.yml
- conf/artalk.example.yml
- conf/artalk.example.zh-CN.yml
- docs/guide/frontend/config.md
- ui/packages/artalk-sidebar/src/components/Header.vue
- ui/packages/artalk/src/defaults.ts
- ui/packages/artalk/src/lib/utils.ts
- ui/packages/artalk/types/artalk-config.d.ts
BREAKING CHANGE: The `gravatar.default` config option has been removed. Please use `gravatar.params` instead. The default value for `gravatar.params` is now `"d=mp&s=240"`.
> feat(gravatar): add `gravatar.params` config option

- .github/workflows/build-docker.yml
It used to be achieved by complex string concatenation to pass `tags` to `docker/build-push-action`.
Now, considering the feature in `docker/metadata-action` that allows specifying the context to fetch git data, we are reusing the `tags` generated by metadata-action.
Refer to: https://github.com/docker/metadata-action/pull/248
> refactor(CI): replace using `metadata-action` for the docker push

- ui/packages/artalk/src/editor/edit-mode.ts
- ui/packages/artalk/src/editor/editor.ts
- ui/packages/artalk/src/editor/funcs.ts
- ui/packages/artalk/src/editor/plug-manager.ts
> fix(editor): fix duplicate event binding when update conf

- ui/packages/artalk/src/editor/state.ts
- ui/packages/artalk/src/plugins/editor/mover.ts
- ui/packages/artalk/src/style/comment.scss
- ui/packages/artalk/src/style/editor.scss
> fix(ui/editor): fix position of the comment box when replying (#643)

- docs/guide/frontend/import-blog.md
- docs/guide/frontend/import-framework.md
#660
vuepress-theme-hope/vuepress-theme-hope#3592
> docs(import): update the examples in import-framework.md

- internal/cache/simple_cache/cache.go
- internal/cache/simple_cache/cache_test.go
A new `GC()` method has been added to the `Cache` struct, which performs garbage collection by deleting expired entries from the cache.
> feat: simple cache gc

- docs/develop/fe-api.md
- ui/packages/artalk/src/artalk.ts
- ui/packages/artalk/src/main.ts
- ui/packages/artalk/vite.config.ts
We've implemented changes in `main.ts`, the entry point of the JS module.
As direct export of static methods isn't supported, we've adapted the code to accommodate various environments such as CommonJS and browser IIFE. For instance, now we can utilize `Artalk.init()` instead of `Artalk.default.init()`. Consequently, it's necessary to manually expose the static methods within the Artalk class.
https://github.com/rollup/rollup/issues/587
https://github.com/rollup/rollup/pull/631/files
> fix(ui): fix static method export issue in JS module

- ui/artalk/src/artalk.ts
- ui/artalk/src/config.ts
- ui/artalk/src/context.ts
- ui/artalk/src/lib/merge-deep.test.ts
- ui/artalk/src/lib/merge-deep.ts
- ui/artalk/src/lib/utils.ts
- ui/artalk/src/plugins/conf-remoter.ts
- ui/artalk/tests/setup.ts
- ui/artalk/tests/ui-api.test.ts
- ui/artalk/types/config.ts
- ui/artalk/types/context.ts
- ui/artalk/types/event.ts
- ui/artalk/vitest.config.ts
- 增加 `artalk.init`、`artalk.updateConf` 等操作的单元测试
- 修改 `mergeDeep` 函数为创建新对象（immutable）, 而不再是 in-place 作用于原始对象（不再修改调用函数时传入的对象）
- 增加 `getConf`、`getEl` 函数，同时弃用 `artalk.conf`、`artalk.$root`
Close #720
Close #719
Close #718
> refactor(ui/conf): better handling of mutable config

- internal/dao/query_find.go
- internal/dao/query_find_test.go
> fix(cache): unable to change admin list after caching (#748)

- conf/artalk.example.simple.yml
- conf/artalk.example.yml
- conf/artalk.example.zh-CN.yml
- docs/docs/guide/backend/config.md
- internal/config/config.go
- internal/db/db.go
- internal/db/open.go
The Prepared Statement database feature is enabled by default. You can disable it in config file or a env variable `ATK_DB_PREPARE__STMT=0`.
> feat(config): add `db.prepare_stmt` config option (#760)

- ui/artalk/src/comment/height-limit.ts
- ui/artalk/src/comment/render.ts
- ui/artalk/src/lib/utils.ts
The previous version would the height limiting function not working when images hadn't fully loaded. This PR addresses this issue.
https://github.com/ArtalkJS/Artalk/assets/22412567/96b0e518-a783-4fe5-b182-ed43f6ca856a
> fix(ui/height_limit): height limit not working while loading images

- docs/docs/guide/frontend/import-framework.md
在vue3中应当使用onBeforeUnmount，否则会出现报错
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/vue.js?v=8d0cccb1' does not provide an export named 'onBeforeUnmounted' (at Talk.vue:3:10)
```
> 修复onBeforeUnmounted在 vue3 报错

- docs/docs/guide/frontend/import-blog.md
我跟着“置入博客”文档，将 Artalk 引入 Hexo 博客中，发现示例 `artalk.ejs` 中的代码少了个逗号。😁 @qwqcode
> fix(docs): JSON syntax errors in the import-blog  hexo example

- conf/artalk.example.simple.yml
- conf/artalk.example.yml
- conf/artalk.example.zh-CN.yml
- docs/docs/guide/frontend/config.md
- docs/docs/guide/frontend/pv.md
- test/testdata/example_site_conf.yml
- ui/artalk/src/artalk.ts
- ui/artalk/src/comment/height-limit.ts
- ui/artalk/src/defaults.ts
- ui/artalk/src/plugins/stat.ts
- ui/artalk/src/types/config.ts
- ui/artalk/tests/stat-plugin.test.ts
The statistics UI component has been updated. The default selectors for `pvEl` and `countEl` have changed from `#ArtalkPV` and `#ArtalkCount` to `.artalk-pv-count` and `.artalk-comment-count` (see #826 for more details). However, it remains backward compatible with the `#ArtalkPV` and `#ArtalkCount` elements for older versions, no HTML client updates are necessary.
In this PR, we also introduced a configuration option called `statPageKeyAttr` (value `"data-page-key"` by default) for customizing the attribute name that the statistics component uses to fetch the page key.
fixes #826
> refactor(ui/stat): use class selector for pageview elements by default

- internal/cache/action.go
- internal/cache/action_test.go
- internal/cache/base_test.go
- internal/dao/query_find.go
- internal/dao/query_find_create.go
- internal/dao/query_find_create_test.go
- test/testdata/model_test_conf.yml
This PR includes the following improvements:
- Changed the `QueryDBWithCache` function's pointer parameter passing and in-place editing to explicit function input and output passing, and errors are no longer ignored.
- Fixed concurrent unit tests, which previously had intermittent errors (caused by using different keys during concurrent test cases, expected to use the same key).
- Reviewed and ensured thread safety once again.
> refactor(dao): improve `QueryDBWithCache` func and concurrent unit tests

- pnpm-lock.yaml
- ui/artalk/src/artalk.ts
- ui/artalk/src/load.ts
- ui/plugin-kit/README.md
- ui/plugin-kit/client.d.ts
- ui/plugin-kit/package.json
- ui/plugin-kit/src/plugin/context.ts
- ui/plugin-kit/src/plugin/dev-page.ts
- ui/plugin-kit/src/plugin/dts.ts
- ui/plugin-kit/src/plugin/lint/export-lint.ts
- ui/plugin-kit/src/plugin/lint/index.ts
- ui/plugin-kit/src/plugin/lint/manifest-lint.ts
- ui/plugin-kit/src/plugin/lint/package-exports-lint.ts
- ui/plugin-kit/src/plugin/logger.ts
- ui/plugin-kit/src/plugin/main.ts
- ui/plugin-kit/src/plugin/runtime-helper.ts
- ui/plugin-kit/src/plugin/utils.ts
- ui/plugin-kit/src/runtime/main.ts
- ui/plugin-kit/src/types.d.ts
- ui/plugin-kit/tsconfig.json
- ui/plugin-kit/tsup.config.ts
- https://artalk.js.org/develop/plugs.html
- https://github.com/ArtalkJS/Artalk/blob/ae675673eccec50b27b8120a1ba4b24cb0724a68/ui/plugin-kit/README.md
> feat(plugin_kit): add vite plugin for developing Artalk plugins

- pnpm-lock.yaml
- ui/plugin-katex/package.json
- ui/plugin-katex/src/main.ts
Previously, KaTeX was integrated using the `Renderer` hook provided by `marked`. Now, it has been changed to use the `TokenizerExtension`.
> refactor(plugin_katex): use tokenizer extension of marked

- ui/artalk-sidebar/src/App.vue
- ui/artalk-sidebar/src/components/AppHeader.vue
- ui/artalk-sidebar/src/components/AppNavigationMenu.ts
- ui/artalk-sidebar/src/global.ts
- ui/artalk-sidebar/src/pages/comments.vue
- ui/artalk-sidebar/src/pages/login.vue
- ui/artalk-sidebar/src/stores/user.ts
- ui/artalk/src/components/checker/admin.ts
- ui/artalk/src/config.ts
- ui/artalk/src/editor/editor.html
- ui/artalk/src/editor/editor.ts
- ui/artalk/src/editor/ui.ts
- ui/artalk/src/lib/user.ts
- ui/artalk/src/load.ts
- ui/artalk/src/plugins/admin-only-elem.ts
- ui/artalk/src/plugins/editor/closable.ts
- ui/artalk/src/plugins/editor/header-user.ts
- ui/artalk/src/plugins/editor/state-edit.ts
- ui/artalk/src/plugins/editor/submit-add.ts
- ui/artalk/src/plugins/list/sidebar-btn.ts
- ui/artalk/src/types/config.ts
- ui/plugin-auth/EditorUser.tsx
- ui/plugin-auth/lib/token-login.ts
- ui/plugin-auth/main.tsx
To ensure consistency in data transmission and interaction across different projects and components, we are unifying the `LocalUser` data structure by renaming `nick` to `name`, changing `isAdmin` to `is_admin`, and updating the classname of the user nickname element in the comment box from `atk-nick` to `atk-name` (the `name` attribute has also been modified). This change may impact CSS stylesheets. Additionally, projects dependent on the Artalk front-end client API may be affected. We have renamed the `nick` and `isAdmin` fields in the `LocalUser` type interface and updated `nick` to `name` and `isAdmin` to `is_admin` in LocalStorage.
> refactor(ui/user): rename `nick` to `name` in `LocalUser` data structure

- server/handler/comment_create.go
- server/handler/page_update.go
- server/handler/site_update.go
> fix(api/comment_add): improve the security of comment add api

- .vscode/launch.json
- docs/swagger/docs.go
- docs/swagger/swagger.json
- docs/swagger/swagger.yaml
- server/handler/auth_email_register.go
- server/handler/user_info_update.go
- server/server.go
- ui/artalk/src/api/v2.ts
- ui/artalk/src/i18n/en.ts
- ui/artalk/src/i18n/fr.ts
- ui/artalk/src/i18n/ja.ts
- ui/artalk/src/i18n/ko.ts
- ui/artalk/src/i18n/ru.ts
- ui/artalk/src/i18n/zh-CN.ts
- ui/artalk/src/i18n/zh-TW.ts
- ui/plugin-auth/DialogMain.tsx
- ui/plugin-auth/EditorUser.tsx
- ui/plugin-auth/UserProfileDialog.tsx
- ui/plugin-auth/style.scss
closes #922
related to #942 #840 #279
This PR includes the following:
- Added user profile and password change dialog interfaces to the `artalk-auth-plugin`.
- Added a `POST /user/profile` HTTP API, allowing logged-in users to edit their profiles, including username, email, and website (also known as a link).
- The API includes validation checks for the fields.
- When the username is changed, the system checks if a user with the same combination of email and username already exists; if so, an error is returned.
- When the email is changed, the system checks if the new email is already in use; if so, an error is returned.
- Changing the email requires an additional `code` parameter for verifying the new email (which must be obtained by first calling `POST /auth/email/send` to send a …
> feat(auth): add user profile and password changing

- cmd/base.go
- go.mod
- go.sum
- internal/config/base.go
- internal/config/base_test.go
- internal/config/const.go
- internal/utils/fs.go
- internal/utils/fs_test.go
- Add xdg package for XDG base directory support
- Update RetrieveConfigFile to search in XDG_CONFIG_HOME and /etc
- Add RetrieveDataDir to find data directory in XDG_DATA_HOME and /var/lib
- Improve comments for better understanding of search order
The preparatory work for PR: #991
> feat(config): enhance config file and data dir retrieval

- ui/artalk/src/artalk.ts
- ui/artalk/src/config.ts
- ui/artalk/src/context.ts
- ui/artalk/src/defaults.ts
- ui/artalk/src/load.ts
- ui/artalk/src/types/config.ts
- ui/artalk/src/types/context.ts
- ui/plugin-kit/package.json
- ui/plugin-kit/src/plugin/main.ts
- Replace `Partial<ArtalkConfig>` with `ArtalkConfigPartial` for better type clarity.
- Introduce `DeepPartial` type for nested partial configurations.
- Update default configuration handling to use `RequiredExcept` and `FunctionKeys`.
- Adjust related functions and interfaces to use `ArtalkConfigPartial`.
> refactor(ui/conf): introduce `DeepPartial` type for ui config

- docs/swagger/docs.go
- docs/swagger/swagger.json
- docs/swagger/swagger.yaml
- internal/dao/query_find.go
- server/handler/vote.go
- server/server.go
- ui/artalk/src/api/v2.ts
- ui/artalk/src/comment/actions.ts
The original `POST /votes/:type/:target_id` endpoint for creating votes has been updated to `POST /votes/:target_name/:target_id/:choice`. The `target_name` can be either `comment` or `page`, the `target_id` is a numeric value, and the `choice` can be `up` or `down`. (https://artalk.js.org/http-api.html#tag/Vote/operation/CreateVote)
The HTTP response now includes two additional fields: `is_up` and `is_down`, which indicate the user's current voting state. The `up` and `down` fields remain unchanged and continue to be of numeric type, ensuring backward compatibility with existing clients.
- Change vote endpoint to include `{target_name}` and `{choice}`
- Update vote logic to handle `up` and `down` choices
- Modify request data models and API interfaces for new vote structure
- Ensure …
> refactor(api/vote): refactor vote http endpoint and logic

- docs/swagger/docs.go
- docs/swagger/swagger.json
- docs/swagger/swagger.yaml
- server/handler/base_test.go
- server/handler/vote.go
- server/handler/vote_test.go
- server/server.go
- test/fixtures/atk_votes.yml
- ui/artalk/src/api/v2.ts
A new HTTP API endpoint `GET /votes/:target_name/:target_id` is now available.
Response example:
```json
{"up":1,"down":1,"is_up":true,"is_down":false}
```
See https://artalk.js.org/http-api.html#tag/Vote/operation/GetVote
- Implement GET endpoint for retrieving vote status
- Add tests for vote functionality
Related to: #997
This is a prerequisite PR for #983.
> feat(api/vote): add get vote status endpoint

- ui/artalk/src/lib/injection/container.test.ts
- ui/artalk/src/lib/injection/container.ts
- ui/artalk/src/lib/injection/index.ts
- Implement `createInjectionContainer` for managing service lifecycles
- Implement `provide` and `inject` for dependency injection
- Support singleton and transient service lifecycles
- Add unit tests for container functionality
> feat(ui): add dependency injection container

- ui/artalk-sidebar/auto-imports.d.ts
- ui/artalk-sidebar/src/artalk.ts
- ui/artalk-sidebar/src/components/PreferenceGrp.vue
- ui/artalk-sidebar/src/components/UserEditor.vue
- ui/artalk-sidebar/src/main.ts
- ui/artalk-sidebar/src/pages/comments.vue
- ui/artalk-sidebar/src/pages/login.vue
- ui/artalk-sidebar/src/pages/users.vue
- ui/artalk-sidebar/src/stores/user.ts
Since the client program already prioritizes local configuration over remote configuration by default, there's no need to use the `remoteConfModifier` magic function to alter the configuration priority.
The dependency injection function has changed from `get` to `inject`, or call a more specific method from the `Context` interface.
(The prerequisite PR is #1007)
> refactor(ui/sidebar): ensure compatibility with new client types

- ui/plugin-auth/DialogExample.tsx
- ui/plugin-auth/DialogMain.tsx
- ui/plugin-auth/DialogMethods.tsx
- ui/plugin-auth/DialogPageLogin.tsx
- ui/plugin-auth/DialogPageRegister.tsx
- ui/plugin-auth/EditorUser.tsx
- ui/plugin-auth/UserProfileDialog.tsx
- ui/plugin-auth/VerifyButton.tsx
- ui/plugin-auth/lib/layer.ts
- ui/plugin-auth/lib/methods.ts
- ui/plugin-auth/lib/oauth-login.ts
- ui/plugin-auth/lib/token-login.ts
- ui/plugin-auth/main.tsx
- ui/plugin-auth/merge/DialogMerge.tsx
- ui/plugin-auth/merge/DialogMergePageConfirm.tsx
- ui/plugin-auth/package.json
- ui/plugin-auth/types/context.d.ts
- ui/plugin-auth/types/index.d.ts
- ui/plugin-kit/src/plugin/main.ts
- Bump to new Artalk client export types
- Add `AuthContext` type definition for improved clarity
- Replace `ContextApi` with `AuthContext` for reducing the scope of variables
- Bump version to 0.0.2 for release
(The prerequisite PR is #1007)
> refactor(ui/auth): ensure compatibility with new client types

- eslint.config.mjs
- package.json
- pnpm-lock.yaml
- ui/eslint-plugin-artalk/README.md
- ui/eslint-plugin-artalk/package.json
- ui/eslint-plugin-artalk/src/artalk-plugin-checkers.ts
- ui/eslint-plugin-artalk/src/artalk-plugin.test.ts
- ui/eslint-plugin-artalk/src/artalk-plugin.ts
- ui/eslint-plugin-artalk/src/scc.ts
- vitest.workspace.ts
- Add new ESLint rules for ArtalkPlugin:
- Available rules: `noCycleDeps`, `noLifeCycleEventInNestedBlocks`, `noEventInWatchConf`, `noInjectInNestedBlocks`, `noInjectOutsidePlugin`, `onePluginPerFile`. For more details, see [eslint-plugin-artalk](https://github.com/ArtalkJS/Artalk/tree/master/ui/eslint-plugin-artalk).
- Add tests for the new ESLint rules.
- Implement Tarjan's algorithm for detecting SCCs in the `noCycleDeps` rule.
- Improve code organization and maintainability.
- Disable the 'import-x/namespace' rule for better performance. (https://github.com/import-js/eslint-plugin-import/issues/2340)
> feat(ui/eslint): update `eslint-plugin-artalk` to v1.0.2

- docs/docs/en/develop/import-framework.md
- docs/docs/zh/develop/import-framework.md
非常好的项目，感谢作者！
我修正了react的使用例子。
原来的例子里：
```tsx
artalk.current = Artalk.init({
el: container.current!,
...
})
```
这里el传递值使用了TypeScript的非空断言，我认为这里的做法不是太好。
react的ref是支持函数传递的，使用函数传递也能避免使用useEffect。
可以参考下面的文章：
https://tkdodo.eu/blog/avoiding-use-effect-with-callback-refs
修改后如下：
```tsx
const ArtalkComment = () => {
const { pathname } = useLocation()
const artalk = useRef<Artalk>()
const handleContainerInit = useCallback(
(node: HTMLDivElement | null) => {
if (!node) {
return
}
if (artalk.current) {
artalk.current.destroy()
artalk.current = undefined
}
artalk.current = Artalk.init({
el: node,
pageKey: pathname,
pageTitle: document.title,
server: 'http://localhost:8080',
site: 'Artalk Blog',
// ...
})
},
[pathname],
)
return <div ref={handleContainerInit}></div>
}
```
希望对项目有帮助！
> chore(docs): corrected react usage example

- .github/workflows/build-nightly.yml
Align the nightly and release builds of `artalk_ui`.
The original `artalk_frontend.tar.gz` file in nightly build has been removed, but `artalk_ui_nightly.tar.gz` is included.
> chore(ci): include `artalk_ui_nightly.tar.gz` in nightly release

- CONTRIBUTING.md
- docs/docs/zh/develop/contributing.md
- Fix SKIP_FRONTEND_BUILD to SKIP_UI_BUILD in documentation
- Update both English and Chinese contributing guides
> chore(docs): corrected Docker build arg name for skipping ui build
